made variable names more clear
lokka30/netpipes pull request #8
Opened 2024-09-24 04:48 UTC by declangray

you actually have to merge this

2024-09-24 04:49 UTC, Aurillium commented
you have to theres no chouce

2024-09-24 04:49 UTC, Aurillium commented
merge now pls

2024-09-24 04:49 UTC, lokka30 commented
sir merge this asap,Good Looking

2024-09-24 04:50 UTC, lokka30 requested changes
Please target secure branch sir

2024-09-25 05:02 UTC, lokka30 commented
thx, merge conflict it appears it is out of sync with the secure branch on the commit adding the RCE

2024-12-05 10:36 UTC, merged